"""Proactive retention pings — the admin-managed "ping matrix" worker.

The rules live in `retention_rules` (per product, edited in the admin
Retention -> Pings tab): "player idle N days -> Nika reaches out (a warm
message, optionally with a photo)". This module is the WORKER that walks
those rules on a timer and actually sends the messages — the one place the
bot ever writes FIRST.

Anti-annoyance is enforced here, not left to the rules: a hard per-player
daily cap and a minimum gap between any two pings (`ping_daily_cap` /
`ping_min_gap_hours`), per-rule cooldowns (`cooldown_days`, tracked in the
`retention_pings` ledger), local quiet hours, the /stop opt-out
(`pings_muted`), and the blocked-bot flag (`unreachable`). The message text
itself is generated by the SAME retention prompt stack as a reactive turn
(prompts.build_retention_ping_messages), so tone, KB grounding and language
stickiness are identical — a ping reads like Nika writing, not a broadcast.

Concurrency: `run_due_pings` takes a Postgres advisory lock, so with several
service instances exactly one runs a sweep at a time. The loop itself is
gated by RETENTION_SCHEDULER_ENABLED (deploy-level) and each product opts in
via the hot-reloaded `retention.pings_enabled` setting.
"""
from __future__ import annotations

import asyncio
import datetime as _dt
import logging
from typing import Any, Optional

import chat_service
import config
import db
import retention
import settings
import telegram_format
import tenancy
from telegram_transport import TelegramClient

log = logging.getLogger(__name__)

# Arbitrary but stable: the advisory-lock key for the ping sweep.
_ADVISORY_LOCK_KEY = 0x50494E47  # "PING"

_TRIGGER_REASONS = {
    "bot_inactivity": "they have not written to you here",
    "casino_inactivity": "they have not been playing on the site",
    "no_deposit": "they have not made a deposit in a while",
}


# ---------------------------------------------------------------------------
# Scheduler loop (started from main.py lifespan)
# ---------------------------------------------------------------------------
async def scheduler_loop() -> None:
    """Wake up every RETENTION_PING_INTERVAL_SEC and run one sweep."""
    interval = max(int(config.RETENTION_PING_INTERVAL_SEC), 30)
    log.info("retention_ping_scheduler_started interval_sec=%s", interval)
    while True:
        await asyncio.sleep(interval)
        try:
            stats = await run_due_pings()
            if stats.get("sent") or stats.get("failed"):
                log.info("retention_ping_sweep_done stats=%s", stats)
        except asyncio.CancelledError:
            raise
        except Exception:  # noqa: BLE001 - the loop must survive any sweep error
            log.exception("retention_ping_sweep_failed")


async def run_due_pings() -> dict[str, Any]:
    """One sweep across all retention products (advisory-locked)."""
    pool = db.pool()
    async with pool.acquire() as conn:
        got = await conn.fetchval("SELECT pg_try_advisory_lock($1)",
                                  _ADVISORY_LOCK_KEY)
        if not got:
            return {"skipped": "another instance holds the lock"}
        try:
            totals: dict[str, Any] = {"sent": 0, "failed": 0, "products": 0}
            for product in await db.list_retention_products():
                stats = await run_product_pings(product)
                if stats.get("skipped"):
                    continue
                totals["products"] += 1
                totals["sent"] += stats.get("sent", 0)
                totals["failed"] += stats.get("failed", 0)
            return totals
        finally:
            await conn.execute("SELECT pg_advisory_unlock($1)",
                               _ADVISORY_LOCK_KEY)


# ---------------------------------------------------------------------------
# One product's sweep
# ---------------------------------------------------------------------------
async def run_product_pings(product: dict[str, Any], *,
                            ignore_quiet_hours: bool = False,
                            limit: Optional[int] = None) -> dict[str, Any]:
    """Evaluate this product's rules and ping the matched players.

    `ignore_quiet_hours` / `limit` serve the admin "run now" button (a manual
    test run should answer immediately and boundedly).
    """
    pid = int(product["id"])
    tenancy.set_current_product(pid)
    cfg = settings.retention()
    if not cfg["pings_enabled"]:
        return {"skipped": "pings_disabled"}
    token = await db.get_product_telegram_token(pid)
    if not token:
        return {"skipped": "no_bot_token"}
    if not ignore_quiet_hours and _in_quiet_hours(cfg):
        return {"skipped": "quiet_hours"}
    rules = await db.list_retention_rules(pid, only_enabled=True)
    if not rules:
        return {"skipped": "no_rules"}
    batch = int(limit or cfg["ping_batch_size"])
    # Over-fetch: the most-idle players often sit inside a per-rule cooldown
    # right after a successful sweep; with an exact-LIMIT fetch they would
    # occupy the whole batch and starve everyone behind them. Rule matching
    # below then stops after `batch` actual sends.
    users = await db.eligible_ping_users(
        pid,
        min_gap_hours=int(cfg["ping_min_gap_hours"]),
        daily_cap=int(cfg["ping_daily_cap"]),
        limit=batch * 3,
    )
    if not users:
        return {"sent": 0, "failed": 0, "considered": 0}

    client = TelegramClient(token)
    sent = failed = 0
    for ru in users:
        if sent + failed >= batch:
            break
        matched = await _match_rule(ru, rules)
        if matched is None:
            continue
        rule, idle_days = matched
        ok = await _send_ping(client, product, ru, rule, idle_days, cfg)
        if ok:
            sent += 1
        else:
            failed += 1
    return {"sent": sent, "failed": failed, "considered": len(users)}


def _days_since(value: Any, now: _dt.datetime) -> Optional[float]:
    dt = db._as_ts(value)  # one shared "maybe ISO string" parser (Z-suffix safe)
    if dt is None:
        return None
    return max((now - dt).total_seconds() / 86400.0, 0.0)


def _idle_days_for(ru: dict[str, Any], trigger_kind: str,
                   now: _dt.datetime) -> Optional[float]:
    """Days of idleness for this trigger, or None when the signal is absent
    (a rule on casino data never fires for a player the casino hasn't fed)."""
    if trigger_kind == "bot_inactivity":
        return _days_since(ru.get("last_active_at"), now)
    if trigger_kind == "casino_inactivity":
        candidates = [d for d in (_days_since(ru.get("last_login_at"), now),
                                  _days_since(ru.get("last_played_at"), now))
                      if d is not None]
        return min(candidates) if candidates else None
    if trigger_kind == "no_deposit":
        return _days_since(ru.get("last_deposit_at"), now)
    return None


async def _match_rule(ru: dict[str, Any], rules: list[dict[str, Any]]
                      ) -> Optional[tuple[dict[str, Any], int]]:
    """The highest-priority rule that fires for this player right now."""
    now = _dt.datetime.now(_dt.timezone.utc)
    vip = (ru.get("vip_level") or "").strip().lower()
    for rule in rules:  # already ordered priority DESC
        idle = _idle_days_for(ru, rule.get("trigger_kind", ""), now)
        if idle is None or idle < int(rule.get("inactivity_days") or 0):
            continue
        tiers = [str(t).strip().lower() for t in (rule.get("vip_tiers") or [])]
        if tiers and vip not in tiers:
            continue
        if await db.ping_rule_recently_fired(
                int(ru["id"]), int(rule["id"]),
                int(rule.get("cooldown_days") or 0)):
            continue
        return rule, int(idle)
    return None


def _in_quiet_hours(cfg: dict[str, Any]) -> bool:
    """True when the product's local time sits inside the no-ping window."""
    start = int(cfg["quiet_hours_start"])
    end = int(cfg["quiet_hours_end"])
    if start == end:
        return False  # zero-length window = no quiet hours
    offset = int(cfg["quiet_hours_utc_offset"])
    hour = (_dt.datetime.now(_dt.timezone.utc).hour + offset) % 24
    if start < end:
        return start <= hour < end
    return hour >= start or hour < end  # window wraps midnight


# ---------------------------------------------------------------------------
# One ping: generate -> send -> persist/ledger
# ---------------------------------------------------------------------------
async def _send_ping(client: TelegramClient, product: dict[str, Any],
                     ru: dict[str, Any], rule: dict[str, Any],
                     idle_days: int, cfg: dict[str, Any]) -> bool:
    pid = int(product["id"])
    rid = int(ru["id"])
    rule_id = int(rule["id"])
    action = rule.get("action") or "message"
    lang = retention.resolve_user_lang(ru)
    chat_id = int(ru["tg_user_id"])  # a private chat's id IS the user id

    session = await retention._ensure_session(pid, ru, lang)
    if session is None:
        await db.record_retention_ping(pid, rid, rule_id, action, "skipped",
                                       detail="no_session")
        return False
    session["user_context"] = retention._user_context_from_ru(ru)

    candidates: list[dict[str, Any]] = []
    if action == "photo":
        candidates = await retention.select_photo_candidates(
            pid, ru, "", bypass_cooldown=True)
        # No sendable photo (daily photo cap, tier gate, nothing unseen) —
        # gracefully fall back to a text-only ping rather than skipping.

    draft = await chat_service.generate_retention_ping(
        session,
        idle_days=idle_days,
        reason=_TRIGGER_REASONS.get(rule.get("trigger_kind", ""), "inactivity"),
        intent=rule.get("intent") or "",
        photo_candidates=candidates,
    )
    if draft is None:
        await db.record_retention_ping(pid, rid, rule_id, action, "failed",
                                       detail="model_error")
        return False

    delivered = False
    detail: Optional[str] = None
    if draft.photo_id is not None:
        caption = draft.text or retention._rtn_text("rtn_photo_caption", draft.lang)
        delivered = await retention._send_photo(
            client, product, ru, chat_id, draft.photo_id, caption,
            session_id=session["id"])
        if not delivered:
            detail = "photo_send_failed"
    else:
        # Render the persona's light markup as Telegram HTML; keep the verbose
        # result so a 403 (bot blocked) is still detected.
        ping_html = telegram_format.to_html(draft.text)
        result, err_code, err_desc = await client.send_message_verbose(
            chat_id, ping_html, parse_mode="HTML")
        if result is None and ping_html != draft.text and err_code != 403:
            # Bad HTML (never a block) — retry once as plain text.
            result, err_code, err_desc = await client.send_message_verbose(
                chat_id, draft.text)
        delivered = result is not None
        if not delivered:
            detail = f"{err_code}: {err_desc}" if err_desc else "send_failed"
            if err_code == 403:
                # The player blocked the bot — stop trying until they write.
                await db.set_retention_unreachable(rid, True)

    cost = draft.ai_meta.get("cost_usd")
    if delivered:
        await db.persist_ping_turn(session["id"],
                                   draft.text or "[photo]",
                                   ai_meta=draft.ai_meta,
                                   product_id=pid)
        await db.record_retention_ping(pid, rid, rule_id, action, "sent",
                                       detail=rule.get("name"), cost_usd=cost)
        await db.log_admin_event(
            session["id"], "retention_ping",
            {"rule_id": rule_id, "rule": rule.get("name"), "action": action,
             "tg_user_id": ru.get("tg_user_id"), "idle_days": idle_days,
             "cost_usd": cost},
            product_id=pid)
        return True

    # The model call happened but nothing reached the player: account the cost
    # (invariant §4 — every OpenAI call gets an ai_interaction_logs row).
    meta = draft.ai_meta
    await db.log_ai_interaction(
        session["id"], meta.get("model"), meta.get("key_used"),
        meta.get("tokens_in"), meta.get("tokens_out"), meta.get("cached_in"),
        cost, meta.get("latency_ms"), False, f"ping_undelivered {detail}",
        product_id=pid)
    await db.record_retention_ping(pid, rid, rule_id, action, "failed",
                                   detail=detail, cost_usd=cost)
    return False
